# Generated by Django 5.2.8 on 2025-11-19 21:13

from django.db import migrations


def create_basic_user(apps, schema_editor):
    User = apps.get_model("auth", "User") 

    username = "test_user"
    password = "Test&Admin"

    # Avoid creating duplicates
    if not User.objects.filter(username=username).exists():
        User.objects.create_user(
            username=username,
            password=password
        )

def delete_basic_user(apps, schema_editor):
    User = apps.get_model("auth", "User")
    User.objects.filter(username="test_user").delete()

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_basic_user, delete_basic_user),
    ]
