version: '3.9'

services:
  db:
    image: postgres:16
    container_name: snipbox_postgres
    restart: always
    env_file:
      - .env
    ports:
      - "${DB_EXPOSED_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django:
    build: .
    container_name: snipbox_django
    command: gunicorn snipbox.wsgi:application --bind 0.0.0.0:${DJANGO_PORT} --workers 3 --reload
    env_file:
      - .env
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
    ports:
      - "${DJANGO_EXPOSED_PORT}:${DJANGO_PORT}"
    depends_on:
      - db

volumes:
  postgres_data: